name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        if: github.event_name != 'release'
        with:
          path: |
            ~/.npm
            node_modules
            build
            .svelte-kit
          key: ${{ github.head_ref || 'main' }}
          restore-keys: |
            main
      - run: npm install
      - run: npm run lint
      - run: npm run build
